theme: jekyll-theme-cayman
title: 2nd Annual Network Science Research Symposium
description: Platform for diverse research, conversation and collaborative atmosphere in Network Science
plugins:
  - jemoji
